command_timeout = 600
format = """
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$python\
$line_break\
$jobs\
$time\
$status\
$os\
$container\
$shell\
$character"""
